### ISSUE TITLE
API crashed, but didn't restart (v3.2.1)

### ISSUE THREAD

**Issue by lacendarko** [balena-io/open-balena#109]
Hi, I'm using the version 3.2.1 of open-balena, it's deployed on a ubuntu server. It's been running for about a month now without any problems. But suddenly it stopped working. When I checked the logs, I saw the API crashed but didn't restart. Here is the log snippet:

Mar 09 13:38:48 c1ad99ddabe7 api[986]: WHERE ("device"."id") IS NOT NULL AND ("device"."id") = ($2)
Mar 09 13:38:48 c1ad99ddabe7 api[986]: LIMIT 1 [ 11, 7 ]
Mar 09 13:38:53 c1ad99ddabe7 api[986]: Error: connect ETIMEDOUT 140.82.121.6:443
Mar 09 13:38:53 c1ad99ddabe7 api[986]:     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
Mar 09 13:38:53 c1ad99ddabe7 api[986]: Program node index.js exited with code 1

**Comment by maggie0002** [comment]
https://forums.balena.io/t/openbalena-crash-error-getaddrinfo-enotfound-api-github-com/285697/3?u=maggie

**Comment by lacendarko** [comment]
Setting `PRODUCTION_MODE: "true"` fixed the problem.
