### ISSUE TITLE
Breaking changes (tunnel.mydomain.com)? 

### ISSUE THREAD

**Issue by maggie44** [balena-io/open-balena#110]
Seems like a new commit requires tunnel.my.domain.com CNAME to be added? 

Would be helpful if that could be included in the changelog. https://github.com/balena-io/open-balena/blob/master/CHANGELOG.md#2021-01-22-6

I review them before upgrades, anticipating breaking changes would be included.

**Comment by ab77** [comment]
Hello again. There are now Renovate nested change logs in the PRs, for [example](https://github.com/balena-io/open-balena/pull/228). That should at least make it easier to track changes, also the fact that there are synthetic tests now..
