### ISSUE TITLE
Production image for supported boards

### ISSUE THREAD

**Issue by vedicium** [balena-io/open-balena#12]
There's no support for creating a production image for the supported boards. According to the [BalenaOS Documentation](https://www.balena.io/docs/reference/OS/overview/2.x/#dev-vs-prod-images), the differences between a production image and a development image are the following (in short):

- Passwordless SSH via port 22222
- Docker socket exposed to port 2377
- Getty console attached to tty1 and serial
- Capable of entering local mode

And probably more. Obviously these are cool and handy things when developing your application. However, in production these functions are a huge security risk. 

This issue is resulting from the [openBalena Topic](https://forums.balena.io/t/device-not-online-production/4319/3) I've created. I know it's in development, but, as suggested, I've created an issue for this function.

**Comment by dfunckt** [comment]
@vedicium [balena.io/os](https://www.balena.io/os/#download) now provides the option to download either a development or production image. Thanks for the nudge!

In the future, we'll also provide the ability to switch between prod and dev *without reflashing*, but this is still in very early stages so I'll be closing this issue.
