### ISSUE TITLE
connect to devices behind an SSH Bastion Host by using ssh ProxyCommand or ProxyJump

### ISSUE THREAD

**Issue by saveriogzz** [balena-io/open-balena#136]
Hi Balena peeps!

I am trying to see my devices on my balenaCloud dashboard but I'm struggling because the network that the devices are connect to is pretty closed and hosts can be reached just by first passing through a [Bastion Host](https://en.wikipedia.org/wiki/Bastion_host). Which I normally do by having either a ProxyJump or a ProxyCommand set in my `.ssh/config` file, for example:

```bash
Host mybastion
    HostName linux-bastion-ex.domain.somewehere
    User saymynamesaymyname

Host somehostonthenetwork
  HostName some-host.department.domain.somewehere
  User saymynamesaymyname
  # either
  ProxyCommand ssh mybastion -W %h:%p
  # or
  ProxyJump mybastion
```

Is there any chance to set this option on balenaCloud/openBalena? I see that there is [support for proxies](https://www.balena.io/docs/reference/balena-cli/#proxy-setup-for-balena-ssh), however I'm not sure it is technically the same thing!

Thanks in advance for your help, I really appreciate it! openBalena is a fantastic project 🐳

**Comment by dfunckt** [comment]
Hey @saveriogzz, thanks for your kind words. I'll have to ask you to direct your inquiries to [our forums](https://forums.balena.io/c/open-balena/46),both the balena team and many openBalena users hang out there and is the best place to get help. We ask that Github issues are reserved for actionable items only. Thanks!

**Comment by saveriogzz** [comment]
hey @dfunckt, thanks! I posted it [there already](https://forums.balena.io/t/how-to-make-balena-connecting-to-devices-behind-a-bastion/352003) but I was not sure it was the best way to approach it. Please go ahead and close or remove this issue :) Cheers

**Comment by ab77** [comment]
Resolved.
