### ISSUE TITLE
balena CLI push does not seem to match application names correctly

### ISSUE THREAD

**Issue by Dogmans** [balena-io/open-balena#16]
Pushing against nonexistent name (behaviour the same for an existing app):

balena push wibblewobble -s .
? 2 applications found with that name, please select the application you would l
ike to push to (Use arrow keys)
❯ undefined/wibblewobble 
  undefined/wibblewobble

If I remove one of the 2 applications that I have then repeat the command

balena push wibblewobble -s .
\ Uploading source package to balena cloudnull

**Comment by dfunckt** [comment]
@Dogmans `balena push` is not supported on open-balena -- it requires the whole balenaCloud infrastructure as it performs a remote build on the cloud builder, similar to `git push`. We plan to offer feedback when invoking CLI commands that aren't supposed to work with open-balena but we're not there yet, apologies for the confusion.

That said, if that error is present when targeting balenaCloud I would appreciate it if you could report it here: https://github.com/balena-io/balena-cli

**Comment by Dogmans** [comment]
Thanks, I will stop trying to use it then!

**Comment by dfunckt** [comment]
@Dogmans, forgot to mention, the commands to look for are `balena build` and `balena deploy`.

**Comment by Dogmans** [comment]
Great, much appreciated
