### ISSUE TITLE
balena API endpoints for post requests not working

### ISSUE THREAD

**Issue by James-kamwendo** [balena-io/open-balena#174]
## Expected Behavior
Im trying to follow through the API documentation for balena and am using it in django, i've tried to get data from my balena server that is hosted on my local server in virtualbox, and the get request are working just fine but when i try to create say a fleet following the documentation the response is 500 but when i use the balena cli its creating the fleet without a problem so i thought maybe am doing it wrong in django and i tried to curl on terminal the Post request for creating a fleet and i did verbose the response was also 500 but the same endpoint am able to get the fleets i created on balena cli, i tried to curl the delete request this one worked but Posting no, i also tried to patch an existing fleet to Enable automatic update tracking for a fleet using curl it said bad request and ive been trying for 4 days now  

## Actual Behavior
Jamess-MacBook-Pro:~ jameskamwendo$ curl --cacert ca.crt -X POST "https://api.balenaproject.net/v6/application" -H "Content-Type: application/json" -H "Authorization: Bearer <MY_AUTH_TOKEN>" --data '{"app_name": "fooled", "is_of_device_type": "raspberrypicm4-ioboard"}' -v
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 192.168.43.207...
* TCP_NODELAY set
* Connected to api.balenaproject.net (192.168.43.207) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: ca.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Unknown (8):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Client hello (1):
* TLSv1.3 (OUT), TLS Unknown, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=*.balenaproject.net
*  start date: Jul 28 13:08:58 2023 GMT
*  expire date: Jul 27 13:08:58 2025 GMT
*  subjectAltName: host "api.balenaproject.net" matched cert's "*.balenaproject.net"
*  issuer: CN=ca.balenaproject.net
*  SSL certificate verify ok.
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
> POST /v6/application HTTP/1.1
> Host: api.balenaproject.net
> User-Agent: curl/7.53.1
> Accept: */*
> Content-Type: application/json
> Authorization: Bearer <........>
> Content-Length: 69
> 
* upload completely sent off: 69 out of 69 bytes
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS Unknown, Unknown (23):
< HTTP/1.1 500 Internal Server Error
< X-Frame-Options: DENY
< X-Content-Type-Options: nosniff
< Vary: X-HTTP-Method-Override
< Cache-Control: no-cache
< Date: Thu, 17 Aug 2023 13:26:15 GMT
< Keep-Alive: timeout=5
< Transfer-Encoding: chunked
< 
* Connection #0 to host api.balenaproject.net left intact
Jamess-MacBook-Pro:~ jameskamwendo$ 

## Specifications
- OS:

**Comment by James-kamwendo** [comment]
Thank you for responding, the documentation is like this: 
curl -X POST \
"https://api.balena-cloud.com/v6/application" \
-H  "Content-Type: application/json"  \
-H "Authorization: Bearer <AUTH_TOKEN>" \
--data '{
    "app_name": "<NAME>",
    "device_type": "<DEVICE TYPE>"
}'

and i did this i was getting this: Jamess-MacBook-Pro:~ jameskamwendo$ curl --cacert ca.crt -X POST "https://api.balenaproject.net/v6/application" -H "Content-Type: application/json" -H "Authorization: Bearer HgZNAhxvD4O7kk1qfyJxavz1dmqZo1Xn" --data '{"app_name": "fooled", "device_type": "raspberrypicm4-ioboard"}' -v
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 192.168.43.207...
* TCP_NODELAY set
* Connected to api.balenaproject.net (192.168.43.207) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: ca.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Unknown (8):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Client hello (1):
* TLSv1.3 (OUT), TLS Unknown, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=*.balenaproject.net
*  start date: Jul 28 13:08:58 2023 GMT
*  expire date: Jul 27 13:08:58 2025 GMT
*  subjectAltName: host "api.balenaproject.net" matched cert's "*.balenaproject.net"
*  issuer: CN=ca.balenaproject.net
*  SSL certificate verify ok.
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
> POST /v6/application HTTP/1.1
> Host: api.balenaproject.net
> User-Agent: curl/7.53.1
> Accept: */*
> Content-Type: application/json
> Authorization: Bearer HgZNAhxvD4O7kk1qfyJxavz1dmqZo1Xn
> Content-Length: 63
> 
* upload completely sent off: 63 out of 63 bytes
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS Unknown, Unknown (23):
< HTTP/1.1 500 Internal Server Error
< X-Frame-Options: DENY
< X-Content-Type-Options: nosniff
< Vary: X-HTTP-Method-Override
< Cache-Control: no-cache
< Date: Thu, 17 Aug 2023 11:55:10 GMT
< Keep-Alive: timeout=5
< Transfer-Encoding: chunked
< 
* Connection #0 to host api.balenaproject.net left intact
Jamess-MacBook-Pro:~ jameskamwendo$

so i think i posted a log of what i was just trying after seeing the reponse when i created a fleet with balena cli the json had the is_of__device_type sort of so i thought maybe this might work just being desperate to see it work

**Comment by dfunckt** [comment]
`is_of__device_type` must be a number, the ID of the device type.

`device_type` as per documentation must be a string, the *slug* of the device type.

Either of the two should work, assuming the API knows about the `raspberrypicm4-ioboard` which I understand is a custom one.

**Comment by James-kamwendo** [comment]
Same reponse am getting in django, code snippet is like the following: 
if request.method == 'POST':
    api_url = "https://api.balenaproject.net/v6/application"
        
        app_name = request.POST.get('app_name')
        device_type = request.POST.get('device_type')
        
        headers_create = {
            "Content-Type": "application/json",
            "Authorization": f"Bearer {auth_token}"
        }
        
        payload = {
            "app_name": app_name,
            "device_type": device_type
        }

        print(payload)

        # device_type
        
        # response = requests.post(api_url, json=payload, headers=headers_create, verify=True)
        response = requests.request('POST', api_url, json=payload, headers=headers_create, verify=True)

        print("Response Content:", response)

**Comment by James-kamwendo** [comment]
> `is_of__device_type` must be a number, the ID of the device type.
> 
> `device_type` as per documentation must be a string, the _slug_ of the device type.
> 
> Either of the two should work, assuming the API knows about the `raspberrypicm4-ioboard` which I understand is a custom one.

I retried it with the is_of__device_type and put a number that was assigned to an existing fleet i created with balena cli and i still get thi:

Jamess-MacBook-Pro:~ jameskamwendo$ curl --cacert ca.crt -X POST "https://api.balenaproject.net/v6/application" -H "Content-Type: application/json" -H "Authorization: Bearer HgZNAhxvD4O7kk1qfyJxavz1dmqZo1Xn" --data '{"app_name": "fooled", "is_of__device_type": 65}' -v
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 192.168.43.207...
* TCP_NODELAY set
* Connected to api.balenaproject.net (192.168.43.207) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: ca.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Unknown (8):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Client hello (1):
* TLSv1.3 (OUT), TLS Unknown, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=*.balenaproject.net
*  start date: Jul 28 13:08:58 2023 GMT
*  expire date: Jul 27 13:08:58 2025 GMT
*  subjectAltName: host "api.balenaproject.net" matched cert's "*.balenaproject.net"
*  issuer: CN=ca.balenaproject.net
*  SSL certificate verify ok.
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
> POST /v6/application HTTP/1.1
> Host: api.balenaproject.net
> User-Agent: curl/7.53.1
> Accept: */*
> Content-Type: application/json
> Authorization: Bearer HgZNAhxvD4O7kk1qfyJxavz1dmqZo1Xn
> Content-Length: 48
> 
* upload completely sent off: 48 out of 48 bytes
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS Unknown, Unknown (23):
< HTTP/1.1 500 Internal Server Error
< X-Frame-Options: DENY
< X-Content-Type-Options: nosniff
< Vary: X-HTTP-Method-Override
< Cache-Control: no-cache
< Date: Thu, 17 Aug 2023 14:16:52 GMT
< Keep-Alive: timeout=5
< Transfer-Encoding: chunked
< 
* Connection #0 to host api.balenaproject.net left intact
Jamess-MacBook-Pro:~ jameskamwendo$ curl --cacert ca.crt -X POST "https://api.balenaproject.net/v6/application" -H "Content-Type: application/json" -H "Authorization: Bearer HgZNAhxvD4O7kk1qfyJxavz1dmqZo1Xn" --data '{"app_name": "fooled", "is_of__device_type": "65"}' -v
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 192.168.43.207...
* TCP_NODELAY set
* Connected to api.balenaproject.net (192.168.43.207) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: ca.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Unknown (8):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Client hello (1):
* TLSv1.3 (OUT), TLS Unknown, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=*.balenaproject.net
*  start date: Jul 28 13:08:58 2023 GMT
*  expire date: Jul 27 13:08:58 2025 GMT
*  subjectAltName: host "api.balenaproject.net" matched cert's "*.balenaproject.net"
*  issuer: CN=ca.balenaproject.net
*  SSL certificate verify ok.
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
> POST /v6/application HTTP/1.1
> Host: api.balenaproject.net
> User-Agent: curl/7.53.1
> Accept: */*
> Content-Type: application/json
> Authorization: Bearer HgZNAhxvD4O7kk1qfyJxavz1dmqZo1Xn
> Content-Length: 50
> 
* upload completely sent off: 50 out of 50 bytes
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS Unknown, Unknown (23):
< HTTP/1.1 500 Internal Server Error
< X-Frame-Options: DENY
< X-Content-Type-Options: nosniff
< Vary: X-HTTP-Method-Override
< Cache-Control: no-cache
< Date: Thu, 17 Aug 2023 14:17:05 GMT
< Keep-Alive: timeout=5
< Transfer-Encoding: chunked
< 
* Connection #0 to host api.balenaproject.net left intact
Jamess-MacBook-Pro:~ jameskamwendo$

**Comment by dfunckt** [comment]
Sorry, I don't see what's wrong. I'll close the issue as the issue tracker is not for support questions, but please post your issue in [our forums](https://forums.balena.io/c/product-support/42), you'll also reach a much wider audience there.
