### ISSUE TITLE
Up to date version of open-balena api requires API_HOST, not HOST env var

### ISSUE THREAD

**Issue by brynmathias** [balena-io/open-balena#178]
Line in api code is:
https://github.com/balena-io/open-balena-api/blob/df219c87659a70f6f3647e882d716085bcfe65f8/src/lib/config.ts#L60

but in compose file we only reference `HOST`:
https://github.com/balena-io/open-balena/blob/ea07d43c5c7e98bb8b11c808b12428a46019c8d5/compose/services.yml#L31C7-L31C11

**Comment by ab77** [comment]
It needs [both](https://github.com/balena-io/open-balena/blob/master/docker-compose.yml#L98). The resolution happens [here](https://github.com/balena-io-modules/open-balena-base/blob/master/src/configure-balena.sh).
