### ISSUE TITLE
device is online=false

### ISSUE THREAD

**Issue by matiasAS** [balena-io/open-balena#180]
Why do I see my fake device online? I can access via ssh and deploy without problems

version services in my server:
(compose/versions)
export OPENBALENA_API_VERSION_TAG=latest
export OPENBALENA_DB_VERSION_TAG=latest
export OPENBALENA_MDNS_PUBLISHER_VERSION_TAG=latest
export OPENBALENA_REGISTRY_VERSION_TAG=latest
export OPENBALENA_S3_VERSION_TAG=latest
export OPENBALENA_VPN_VERSION_TAG=latest

balena cli version: 17.4.2

![image](https://github.com/balena-io/open-balena/assets/7276332/2f45721e-20bd-47b1-bb16-99577cba2232)

I remain attentive to comments

**Comment by ab77** [comment]
You probably want to give the [latest](https://open-balena.pages.dev/getting-started/) version a try, you have quote a few issues open and I suspect some of these have gone stale, closing.
