### ISSUE TITLE
deploy multi docker-compose file without replace services

### ISSUE THREAD

**Issue by matiasAS** [balena-io/open-balena#181]
Hello,
I would like to know if it is possible and how to deploy multiple docker-compose.yml without replacing the services, leaving only the last ones running. For example:
deploy 1: 10 services
deploy 2: 5 services

There are only 5 left from deploy 2 and I want 15 to remain

version services in my server:
(compose/versions)
export OPENBALENA_API_VERSION_TAG=latest
export OPENBALENA_DB_VERSION_TAG=latest
export OPENBALENA_MDNS_PUBLISHER_VERSION_TAG=latest
export OPENBALENA_REGISTRY_VERSION_TAG=latest
export OPENBALENA_S3_VERSION_TAG=latest
export OPENBALENA_VPN_VERSION_TAG=latest

balena cli version: 17.4.2

Stay tuned to any comments
greetings
Matias

**Comment by ab77** [comment]
Check out [docker swarm.](https://docs.docker.com/engine/swarm/) or even Kubernetes (kompose can produce a config from a Docker composition).
