### ISSUE TITLE
Restricted API keys

### ISSUE THREAD

**Issue by TimoAtMUV** [balena-io/open-balena#182]
An API token for the Balena cloud is very powerful and anyone who has the API key can have a big impact on devices, e.g. update all environment variables of all devices, it would be great if we could restrict an API key to a subset of fleets.

This would make development cycles much more secure. => Limit an API key to a staging fleet.

**Comment by fisehara** [comment]
@TimoAtMUV Yes this is a valid request. This issue should be located at https://github.com/balena-io/open-balena-api/issues as this is the place where the API keys are managed. 
Right now the open-balena-api is not supporting (fleet) scoped API keys. Eventually this feature will be implemented.
