### ISSUE TITLE
I can't connect to device - balena ssh <uuid device> - Host <UUID> not found: 2(SERVFAIL)

### ISSUE THREAD

**Issue by matiasAS** [balena-io/open-balena#184]
### Description
I'm encountering a persistent problem when attempting to establish an SSH connection to devices managed by openBalena. Despite having the necessary DNS configurations and verified connectivity through nslookup for `ssh.devices.openbalena-sistemasmas.online`, I'm unable to use the `balena ssh <UUID>` command to connect to my devices. The operation fails with the following error:

Although I can successfully establish a connection using `balena tunnel`, I am looking for a resolution to use `balena ssh` due to its more direct, faster, and easier approach.

### Environment
- **openBalena Version**: (utilizing the latest tags as mentioned)
  - OPENBALENA_API_VERSION_TAG=latest
  - OPENBALENA_DB_VERSION_TAG=latest
  - OPENBALENA_MDNS_PUBLISHER_VERSION_TAG=latest
  - OPENBALENA_REGISTRY_VERSION_TAG=latest
  - OPENBALENA_S3_VERSION_TAG=latest
  - OPENBALENA_VPN_VERSION_TAG=v11.26.0
- **balena CLI Version**: 17.4.2
- **Operating System**: Ubuntu 22.04.3
- **Cloud Provider for DNS**: Cloudflare
- **DNS Configuration**: An A record for `ssh.devices` subdomain is provided with "DNS only" setting in Cloudflare.

### Steps to Reproduce
1. Execute the command `balena ssh <UUID>` in the terminal.
2. The error message appears immediately after.

### Current State
- The error blocks the use of the `balena ssh <UUID>` command.
- There is no issue when connecting using `balena tunnel` as an alternative method.

### Attempts to Resolve
- DNS settings have been double-checked for accuracy.
- DNS resolution for `ssh.devices.openbalena-sistemasmas.online` has been confirmed through `nslookup`.
- VPN service logs have been reviewed and show no apparent issues with device connections.

- I am seeking a solution that allows me to use `balena ssh` without the workaround of `balena tunnel`.

I wonder if leaving the DEVICE_CONFIG_SSH_AUTHORIZED_KEYS environment variable empty could be causing the issue, as I have not configured it for my setup. Could this be related to the balena ssh <UUID> command not functioning as expected?

**Comment by ab77** [comment]
openBalena does not have SSH functionality, unlike balenaCloud. You could implement your own using tunnel endpoint provided by open-balena-vpn.
