### ISSUE TITLE
DBUS: Communication with NetworkManager not possible anymore from docker container application

### ISSUE THREAD

**Issue by autonoma-official** [balena-io/open-balena#190]
We have an docker image where a python application will configure the NetworkManager and get the status of the network interfaces over dbus

it worked perfectly but with the new image version 5.2.8 (raspberrypi4-64 it is not possible to get information from NetworkManager over DBUS anymore.

**Comment by ab77** [comment]
This issue is not related to openBalena, you could try searching through the following instead:
https://github.com/balena-os/balena-raspberrypi
https://github.com/balena-os/meta-balena
