### ISSUE TITLE
make auto-pki Command Takes Excessively Long Time to Complete

### ISSUE THREAD

**Issue by matiasAS** [balena-io/open-balena#203]
**Description:**

I am experiencing significant delays when running the make auto-pki command on my openBalena setup. The process takes an unusually long time (more than 15 minutes), and it does not seem to complete successfully. Here is a detailed summary of my environment and the steps I have taken:

**Environment:**

- openBalena Version: Latest (as of May 2024)
- Operating System: Ubuntu Server running in a Proxmox virtual machine
- Network Configuration: Using pfSense with HAProxy
- Backend Servers: Configured to use both HTTP (port 80) and HTTPS (port 443)

**Steps to Reproduce:**

1- Set up openBalena following the official documentation.
2- Configure pfSense with HAProxy to handle both HTTP and HTTPS traffic.

**Run the following commands:**

export ACME_EMAIL=acme@openbalena-sistemasmas-stage.online
export CLOUDFLARE_API_TOKEN=<my_cloudflare_api_token>
make auto-pki

**Troubleshooting Steps Taken:**

1- Verified connectivity to Cloudflare.
2- Reviewed and adjusted HAProxy configuration to handle HTTP and HTTPS separately.
3- Restarted Docker services.
4- Checked for and removed any self-signed certificates that might be causing conflicts.
5- Verified sufficient system resources (CPU, RAM).

Despite these steps, the issue persists. I would appreciate any guidance or suggestions on how to resolve this problem.

**Expected Behavior:**

The make auto-pki command should complete in a reasonable amount of time (under 10 minutes), and the API endpoint should be consistently accessible without errors.

**Additional Information:**

- Attached relevant logs and configuration snippets.
- System is set up in a production-like environment with pfSense managing network traffic.

Thank you for your assistance!

Important note: because my English is not good (i from Chile), I have created the content of this issue with the help (copied) of chat gpt
@florianluediger @roman-mazur @wrboyce @relaxdiego @dfunckt

**Comment by ab77** [comment]
> Attached relevant logs and configuration snippets.

There is nothing attached. You can monitor the logs from `cert-manager` container to see what's going on and where it is failing.

P.S. most of the folks you are pinging have moved on.

**Comment by matiasAS** [comment]
@ab77 I have another question about the api service? Is there another problem?

**Comment by ab77** [comment]
Please move this to the balena Forums, so that the wider community can help with support. GitHub issues are best used for very specific issues with the codebase, ideally discussing around source code/specific lines of code.
