### ISSUE TITLE
'make up' not working

### ISSUE THREAD

**Issue by djohnson-mulytic** [balena-io/open-balena#219]
Hey all, I'm new to this and using the commands here (https://open-balena.pages.dev/getting-started/)
Everything was fine until I got to:

export DNS_TLD=mydomain.com
make up

I get:
Makefile:7: .env: No such file or directory
make: *** No rule to make target '.env'.  Stop.

I am using Ubuntu on AWS, not sure where I've gone wrong, if anyone has ideas, I'd love to hear them. Thanks again

**Comment by ab77** [comment]
There appears to be an issue with a fresh install where the Makefile expects `.env` to exist. Workaround could be a simple `touch .env` prior to running `make up` or changing to Makefile line 7 from `include ..` to `-include ..` cc @klutchell

**Comment by ab77** [comment]
https://github.com/balena-io/open-balena/pull/222

**Comment by ab77** [comment]
@djohnson-mulytic should be fixed now.

**Comment by djohnson-mulytic** [comment]
Wow, you are EXACTLY right, thanks so much for the fast response and getting it working. Really do appreciate you taking the time. Thanks again
