### ISSUE TITLE
Device listed as offline, while online and still communicating with server

### ISSUE THREAD

**Issue by kazazes** [balena-io/open-balena#23]
Running `balena devices` with openBalena, my devices are always labeled as offline. Similar. to #17, but in this case I'm not sure if it's a compatibility problem or something wrong with my installation.

Will feature support between `balena-cli` and openBalena be mitigated over time? For a few commands, there's no openBalena equivalent at all... maybe a fork of `balena-cli` tailored for openBalena?

**Comment by kazazes** [comment]
Only now seeing #9, so that patch didn't quite fix it.

**Comment by dfunckt** [comment]
@kazazes, #9 fixed one part of the issue, the other part is in balenaOS and will be fixed by [os-config#13](https://github.com/balena-os/os-config/pull/13) in the upcoming release.

**Comment by steevegldev** [comment]
It's supposed to be fixed? I have the same issue with balenaOS 2.29.2+rev1. OpenBelana is on master 
Latest commit d3b021a. balena-cli v9.12.0

I don't know how to diagnostic.

The only error could find is this message in the supervisor container from the offline device:
LogBackend: server responded with status code: 504

The application work as expected, but some balena-cli feature require the devices to be online.
