### ISSUE TITLE
Steps to Change Domain in OpenBalena v3.8.2 and v4.0.13

### ISSUE THREAD

**Issue by matiasAS** [balena-io/open-balena#239]
Hi OpenBalena team,

I am currently using OpenBalena v3.8.2 and have migrated my server from AWS to a Proxmox virtual machine hosted on a Hetzner server. To avoid configuration issues, I copied the entire folder via SCP, backed up the database, and then restored it.

I have the following questions regarding changing the domain:

What are the exact steps to change the domain?
Should I run the quickstart command again?
Do I need to delete the certificate folder?
Will there be errors in image downloads on devices after updating the config.json file?
Additionally, for the new version, I am currently on v4.0.13 and have the same questions:

What are the steps to change the domain in v4.0.13?
Should I follow the same procedure as with v3.8.2?
I have deployed OpenBalena on the server, but I haven't tested it on any device yet. Are there any specific steps or precautions I should take?
I've noticed that there are updates almost every day, which is great, and I plan to update regularly. The reason for my question about changing the domain is that the one I'm using to test v4.x has been blacklisted. I want to be prepared in case my only option is to use a new domain.

Thank you for your help!

**Comment by ab77** [comment]
.. from https://open-balena.pages.dev/getting-started/, broadly the following should restart the system on the new domain, assuming it is already setup to point to the public IP of the new server:

```
export DNS_TLD=mydomain.com
rm -r .env
make up
```

**Comment by matiasAS** [comment]
@ab77 ok, it is easy
but, And for the previous version?

**Comment by ab77** [comment]
> @ab77 ok, it is easy but, And for the previous version?

for the previous versions, probably re-running the quickstart is sufficient, but we've not tested it

**Comment by matiasAS** [comment]
@ab77 
And who could help me with that?

**Comment by ab77** [comment]
> @ab77 And who could help me with that?

You could try figuring out a solution, document it and submit a pull request/patch to the relevant codebase(s). The community (forums, GitHub, etc.) may also be able to help - this is generally how open source software works. If that isn't fit for purpose, [signup](https://www.balena.io/) to balenaCloud, which comes with 24/7 support.

**Comment by dfunckt** [comment]
Note that the domain name is baked into image names, so if you change it, the devices will fail to pull existing releases. New releases created after the change will obviously work correctly.

**Comment by matiasAS** [comment]
> > @ab77 And who could help me with that?
> 
> You could try figuring out a solution, document it and submit a pull request/patch to the relevant codebase(s). The community (forums, GitHub, etc.) may also be able to help - this is generally how open source software works. If that isn't fit for purpose, [signup](https://www.balena.io/) to balenaCloud, which comes with 24/7 support.

It is impossible for me to switch to the paid version with 24/7 support. I am an independent developer, I work alone and I cannot afford the 150usd per month.
