### ISSUE TITLE
How to setup CNAME

### ISSUE THREAD

**Issue by py4mac** [balena-io/open-balena#24]
Hello,

I'm trying to setup OpenBalena. I would like to evaluate OpenBalena on my personal laptop running on Ubuntu 18.04 .
From the getting started: https://www.balena.io/open/docs/getting-started, I need to setup CNAME.
Which tool are you using to setup CNAME entries? Do you have any example file for openbalena configuration? 
From my side, I tried the tool bind9 without success. I'm probably missing competencies in this domaine.

If you have already installed OpenBalena, please share your configuration !

Thanks.

Py.

**Comment by dfunckt** [comment]
Hello @py4mac can you please post your question [on the forums](https://forums.balena.io/c/open-balena)? We try to keep Github issues only for actionable items or bug reports. Forums is a much better place for discussion and support related questions.

**Comment by py4mac** [comment]
Thanks for your reply.
No problem. I close this ticket and post my question on the forum.
