### ISSUE TITLE
OpenVPN Issue with "Bad encapsulated packet length from peer"

### ISSUE THREAD

**Issue by matiasAS** [balena-io/open-balena#268]
Server architecture:

Hetzner server
Proxmox
pfSense
Nginx Proxy Manager (NPM)
Cloudflare in front
OpenBalena version 3.8.2.

When the device connects to the VPN, it gives the following errors:

![image](https://github.com/balena-io/open-balena/assets/7276332/969b9101-0f9d-43cc-9ad6-09b980c9711d)

These logs are with the Cloudflare proxy active.

I have tested connecting the server and devices using Tailscale, then configured Cloudflare with the proxy disabled for the server's IP to vpn.<my_domain>, and it works. However, when passing through pfSense, NPM, or even a Cloudflare tunnel, it gives the error. My only alternative seems to be using a public IP for the virtual machine.

Any guidance or suggestions would be appreciated.

Thank you!

**Comment by ab77** [comment]
Looks like you are trying to proxy OpenVNP traffic via CloudFlare. This won' work. Ensure `cloudlink.{{ dns_tld }}` points directly to openBalena backend or at least via a TCP only load balancer.
