### ISSUE TITLE
Add RHEL certificate documentation to quickstart

### ISSUE THREAD

**Issue by cameronwp** [balena-io/open-balena#30]
It looks like the Linux instructions for adding the self-signed cert in the quickstart is Debian specific. Here's what I would add for RHEL users like me. **I'm definitely not an expert in certs**, so please someone check my work - this is just what I figured out after a few minutes of googling.

#### RHEL
```sh
npm config set cafile "/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem" -g
sudo cp path/to/self/signed/cert/ca.crt /etc/pki/ca-trust/source/anchors/
sudo update-ca-trust extract
```

([Here's the documentation on resetting your certs in case something goes wrong](https://access.redhat.com/solutions/1549003))

**Comment by ab77** [comment]
New new [guide](https://open-balena.pages.dev/getting-started/#ssl-configuration) may help here.
