### ISSUE TITLE
Device download progress & state non-functional

### ISSUE THREAD

**Issue by richbayliss** [balena-io/open-balena#31]
Tested using the latest API code, when the device downloads updates to the application stack the fields `status` and `download_progress` remain unchanged.

**Comment by dfunckt** [comment]
@richbayliss is this still an issue or can be closed? Any idea what is/was causing it?

**Comment by dfunckt** [comment]
@richbayliss reping

**Comment by 0x1d** [comment]
Hi @dfunckt we're experiencing the same issue using the current release (balena/armv7hf-supervisor:v10.2.2 on raspberrypi3 and balena/open-balena-api:v0.19.5).

**Comment by lcamargof** [comment]
The issue is unresolved, is also present on supervisor 10.8.0

**Comment by 20k-ultra** [comment]
This is a V1 endpoint which was written before multicontainer existed and unfortunately this regression was created after that switch.

Thankfully, the newer  [GET /v2/applications/:appId/state ](https://www.balena.io/docs/reference/supervisor/supervisor-api/#get-v2applicationsappidstate) endpoint works and provides the same information.

**Comment by 20k-ultra** [comment]
https://github.com/balena-io/open-balena/issues/31 also reports the commit being undefined in the same situation as this issue.

**Comment by dfunckt** [comment]
Should be fixed by #88
