### ISSUE TITLE
redis container is insecure and open to Internet by default, causing malware to eventually disable a newly configured openBalena host

### ISSUE THREAD

**Issue by bandrews** [balena-io/open-balena#34]
**Summary:**  the redis container of openBalena is exposed to the Internet by default with no security enabled, and likely shouldn't be.  

Ideally, the compose configurations for the server should only expose 443 out of box, as per [this forum thread](https://forums.balena.io/t/security-issue-with-redis-on-openbalena-deployment/4272).  That way, openBalena is secure by default and only allows access to other ports via the docker compose-created local network unless explicitly enabled for debugging.  

But at a minimum, even if that can't be done, the quickstart guide needs to be updated with guidance for securing a new install ASAP to explicitly instruct users to block the other ports (looks like 80, 222, 3128, 5432, and 6379?) using a firewall.  It might be worth thinking about other server configuration best practices that the Balena team uses in production that would be applicable to openBalena admins as well.

**Full issue:**  While experimenting with open-balena installed on an Internet-accessible server, I noticed strange behavior where after 6-24 hours of uptime, 'balena logs' would stop working with a "BalenaRequestError: Request error: Internal Server Error" error.  Stopping and restarting all the containers resolved the issue each time, so I got in the habit of temporarily restarting it each day before working with my server.

That eventually caused me to investigate the logs for all the various composed docker containers for the server to root cause what was going on, and I noticed strange logging from redis starting a few hours after the last restart:

```
balena@servername:~/open-balena/compose$ docker logs 26cac86e889a | more
1:C 07 Jan 2019 07:45:39.899 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 07 Jan 2019 07:45:39.899 # Redis version=5.0.3, bits=64, commit=00000000, modified=0, pid=1, just started
1:M 07 Jan 2019 07:45:39.900 * Running mode=standalone, port=6379.
1:M 07 Jan 2019 07:45:39.900 # Server initialized
1:M 07 Jan 2019 07:45:39.900 * DB loaded from disk: 0.000 seconds
1:M 07 Jan 2019 07:45:39.900 * Ready to accept connections
1:M 07 Jan 2019 07:50:40.090 * 100 changes in 300 seconds. Saving...
1:M 07 Jan 2019 07:50:40.091 * Background saving started by pid 12
12:C 07 Jan 2019 07:50:40.116 * DB saved on disk
12:C 07 Jan 2019 07:50:40.117 * RDB: 0 MB of memory used by copy-on-write
1:M 07 Jan 2019 07:50:40.192 * Background saving terminated with success
1:M 07 Jan 2019 07:55:41.026 * 100 changes in 300 seconds. Saving...
1:M 07 Jan 2019 07:55:41.027 * Background saving started by pid 13
13:C 07 Jan 2019 07:55:41.054 * DB saved on disk
13:C 07 Jan 2019 07:55:41.056 * RDB: 0 MB of memory used by copy-on-write
1:M 07 Jan 2019 07:55:41.129 * Background saving terminated with success
1:M 07 Jan 2019 08:17:51.870 * DB saved on disk
1:M 07 Jan 2019 08:17:51.872 # Failed opening the RDB file root (in server root dir /var/spool/cron) for saving: Permission denied
1:M 07 Jan 2019 08:17:51.873 # Failed opening the RDB file root (in server root dir /etc/crontabs) for saving: Permission denied
1:M 07 Jan 2019 09:17:52.046 * 1 changes in 3600 seconds. Saving...
1:M 07 Jan 2019 09:17:52.047 * Background saving started by pid 14
14:C 07 Jan 2019 09:17:52.049 # Failed opening the RDB file root (in server root dir /etc/crontabs) for saving: Permission denied
1:M 07 Jan 2019 09:17:52.149 # Background saving error
1:M 07 Jan 2019 09:17:58.085 * 1 changes in 3600 seconds. Saving...
1:M 07 Jan 2019 09:17:58.086 * Background saving started by pid 15
15:C 07 Jan 2019 09:17:58.087 # Failed opening the RDB file root (in server root dir /etc/crontabs) for saving: Permission denied
1:M 07 Jan 2019 09:17:58.187 # Background saving error
```

_(repeats ~10,000 more times over six days)_

This is suspicious - I wouldn't expect redis to be trying to write out to /var/spool/cron or /etc/crontabs!  And, as it turns out, this is a common symptoms of attackers trying to install cryptominers or other malware through redis as a vector: https://blog.huntingmalware.com/notes/LLMalware#attack

Fortunately, in this case because the redis container is so minimal, it only got as far as changing the password on my database instance.  So it was effectively just a DoS attack - and not a particularly effective one at that.  But my machine gets consistently "reinfected" every time I restart the server after a few hours, and I suspect this will be common in the wild once more people start experimenting with openBalena (particularly in development environments where you might be more lax about setting up a firewall/etc.)

Since balena is managed through docker compose, and it appears these ports are being explicitly exposed through haproxy, my suggestion would be to use that to block access to redis and other services that don't need to be public by default;  developers are always free to expose those ports for debugging/development if necessary, but IMHO at the end of the quickstart you should be left with the minimal surface area necessary for the app to work.

**Comment by dfunckt** [comment]
Hello @bandrews, thanks for the comprehensive report. This is just a quick update to let you know that we agree that we're essentially guiding users to a very insecure installation and gloss over the security issues in our Getting Started guide and that we're discussing a few options to remedy this the soonest possible.

**Comment by bandrews** [comment]
Awesome, thanks for looking into this (and into security all-up).  Glad to hear it's being worked on!

In the interim, I went ahead and adjusted compose/services.yml on my install to move most of the ports from "ports" to "expose", effectively blocking off everything except 443 from the outside world.  I don't expect this to be the only long term fix and there may be hidden consequences in some features I don't use or that aren't lit up yet, but everything seems to be working so far for my admittedly limited purposes:

```
haproxy:
    ports:
      - "443:443"
    expose:
      - "80"
      - "222"
      - "3128"
      - "5432"
      - "6379"
```

**Comment by dfunckt** [comment]
You’ll also need to expose port 3128 for the VPN, but otherwise that should work just fine and not prevent anything from working.
