### ISSUE TITLE
openBalena shuts down unexpected

### ISSUE THREAD

**Issue by t16n** [balena-io/open-balena#37]
After 1-2 the server shuts down unexpected 

Running on:
> AWS Ubuntu Server 18.04 LTS (HVM), SSD Volume Type - t2.micro

Logs:
`redis_1_8f8d336723d1 | 1:C 05 Feb 2019 08:04:42.628 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1_8f8d336723d1 | 1:C 05 Feb 2019 08:04:42.628 # Redis version=5.0.3, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1_8f8d336723d1 | 1:C 05 Feb 2019 08:04:42.628 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis_1_8f8d336723d1 | 1:M 05 Feb 2019 08:04:42.631 * Running mode=standalone, port=6379.
redis_1_8f8d336723d1 | 1:M 05 Feb 2019 08:04:42.631 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1_8f8d336723d1 | 1:M 05 Feb 2019 08:04:42.631 # Server initialized
redis_1_8f8d336723d1 | 1:M 05 Feb 2019 08:04:42.631 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1_8f8d336723d1 | 1:M 05 Feb 2019 08:04:42.631 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis_1_8f8d336723d1 | 1:M 05 Feb 2019 08:04:42.631 * DB loaded from disk: 0.001 seconds
redis_1_8f8d336723d1 | 1:M 05 Feb 2019 08:04:42.631 * Ready to accept connections
redis_1_8f8d336723d1 | 1:M 05 Feb 2019 10:16:49.511 * 1 changes in 3600 seconds. Saving...
redis_1_8f8d336723d1 | 1:M 05 Feb 2019 10:16:49.513 * Background saving started by pid 12
redis_1_8f8d336723d1 | 12:C 05 Feb 2019 10:16:49.518 * DB saved on disk
redis_1_8f8d336723d1 | 12:C 05 Feb 2019 10:16:49.518 * RDB: 0 MB of memory used by copy-on-write
redis_1_8f8d336723d1 | 1:M 05 Feb 2019 10:16:49.613 * Background saving terminated with success
redis_1_8f8d336723d1 | 1:M 05 Feb 2019 11:16:50.076 * 1 changes in 3600 seconds. Saving...
redis_1_8f8d336723d1 | 1:M 05 Feb 2019 11:16:50.076 * Background saving started by pid 13
redis_1_8f8d336723d1 | 13:C 05 Feb 2019 11:16:50.080 * DB saved on disk
redis_1_8f8d336723d1 | 13:C 05 Feb 2019 11:16:50.081 * RDB: 0 MB of memory used by copy-on-write
redis_1_8f8d336723d1 | 1:M 05 Feb 2019 11:16:50.176 * Background saving terminated with success
redis_1_8f8d336723d1 | 1:M 05 Feb 2019 14:23:22.623 * 1 changes in 3600 seconds. Saving...
redis_1_8f8d336723d1 | 1:M 05 Feb 2019 14:23:22.624 * Background saving started by pid 14
redis_1_8f8d336723d1 | 14:C 05 Feb 2019 14:23:22.631 * DB saved on disk
redis_1_8f8d336723d1 | 14:C 05 Feb 2019 14:23:22.631 * RDB: 0 MB of memory used by copy-on-write
redis_1_8f8d336723d1 | 1:M 05 Feb 2019 14:23:22.725 * Background saving terminated with success
redis_1_8f8d336723d1 | 1:M 05 Feb 2019 15:23:23.014 * 1 changes in 3600 seconds. Saving...
redis_1_8f8d336723d1 | 1:M 05 Feb 2019 15:23:23.014 * Background saving started by pid 15
redis_1_8f8d336723d1 | 15:C 05 Feb 2019 15:23:23.019 * DB saved on disk
redis_1_8f8d336723d1 | 15:C 05 Feb 2019 15:23:23.019 * RDB: 0 MB of memory used by copy-on-write
redis_1_8f8d336723d1 | 1:M 05 Feb 2019 15:23:23.115 * Background saving terminated with success
redis_1_8f8d336723d1 | 1:M 05 Feb 2019 16:23:24.054 * 1 changes in 3600 seconds. Saving...
redis_1_8f8d336723d1 | 1:M 05 Feb 2019 16:23:24.059 * Background saving started by pid 16
redis_1_8f8d336723d1 | 16:C 05 Feb 2019 16:23:24.082 * DB saved on disk
redis_1_8f8d336723d1 | 16:C 05 Feb 2019 16:23:24.082 * RDB: 0 MB of memory used by copy-on-write
redis_1_8f8d336723d1 | 1:M 05 Feb 2019 16:23:24.159 * Background saving terminated with success
redis_1_8f8d336723d1 | 1:M 05 Feb 2019 16:44:47.613 * 100 changes in 300 seconds. Saving...
redis_1_8f8d336723d1 | 1:M 05 Feb 2019 16:44:47.616 * Background saving started by pid 17
redis_1_8f8d336723d1 | 17:C 05 Feb 2019 16:44:47.660 * DB saved on disk
redis_1_8f8d336723d1 | 17:C 05 Feb 2019 16:44:47.661 * RDB: 0 MB of memory used by copy-on-write
redis_1_8f8d336723d1 | 1:M 05 Feb 2019 16:44:47.716 * Background saving terminated with success
redis_1_8f8d336723d1 | 1:M 05 Feb 2019 16:49:48.019 * 100 changes in 300 seconds. Saving...
redis_1_8f8d336723d1 | 1:M 05 Feb 2019 16:49:48.023 * Background saving started by pid 18
redis_1_8f8d336723d1 | 18:C 05 Feb 2019 16:49:48.048 * DB saved on disk
redis_1_8f8d336723d1 | 18:C 05 Feb 2019 16:49:48.048 * RDB: 0 MB of memory used by copy-on-write
redis_1_8f8d336723d1 | 1:M 05 Feb 2019 16:49:48.123 * Background saving terminated with success
redis_1_8f8d336723d1 | 1:M 05 Feb 2019 16:54:49.075 * 100 changes in 300 seconds. Saving...
redis_1_8f8d336723d1 | 1:M 05 Feb 2019 16:54:49.075 * Background saving started by pid 19
redis_1_8f8d336723d1 | 19:C 05 Feb 2019 16:54:49.110 * DB saved on disk
redis_1_8f8d336723d1 | 19:C 05 Feb 2019 16:54:49.110 * RDB: 0 MB of memory used by copy-on-write
redis_1_8f8d336723d1 | 1:M 05 Feb 2019 16:54:49.175 * Background saving terminated with success
redis_1_8f8d336723d1 | 1:M 05 Feb 2019 16:59:50.098 * 100 changes in 300 seconds. Saving...
redis_1_8f8d336723d1 | 1:M 05 Feb 2019 16:59:50.099 * Background saving started by pid 20
redis_1_8f8d336723d1 | 20:C 05 Feb 2019 16:59:50.114 * DB saved on disk
redis_1_8f8d336723d1 | 20:C 05 Feb 2019 16:59:50.114 * RDB: 0 MB of memory used by copy-on-write
redis_1_8f8d336723d1 | 1:M 05 Feb 2019 16:59:50.199 * Background saving terminated with success
redis_1_8f8d336723d1 | 1:M 05 Feb 2019 17:04:51.026 * 100 changes in 300 seconds. Saving...
redis_1_8f8d336723d1 | 1:M 05 Feb 2019 17:04:51.026 * Background saving started by pid 21
redis_1_8f8d336723d1 | 21:C 05 Feb 2019 17:04:51.057 * DB saved on disk
redis_1_8f8d336723d1 | 21:C 05 Feb 2019 17:04:51.057 * RDB: 0 MB of memory used by copy-on-write
redis_1_8f8d336723d1 | 1:M 05 Feb 2019 17:04:51.126 * Background saving terminated with success
redis_1_8f8d336723d1 | 1:M 05 Feb 2019 17:09:52.057 * 100 changes in 300 seconds. Saving...
redis_1_8f8d336723d1 | 1:M 05 Feb 2019 17:09:52.071 * Background saving started by pid 22
redis_1_8f8d336723d1 | 22:C 05 Feb 2019 17:09:52.499 * DB saved on disk
redis_1_8f8d336723d1 | 22:C 05 Feb 2019 17:09:52.500 * RDB: 0 MB of memory used by copy-on-write
redis_1_8f8d336723d1 | 1:M 05 Feb 2019 17:09:52.613 * Background saving terminated with success
s3_1_19521a2a2d0e | Systemd init system enabled.
db_1_7ad66e59518a | 2019-02-05 08:04:43.797 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1_7ad66e59518a | 2019-02-05 08:04:43.797 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1_7ad66e59518a | 2019-02-05 08:04:43.826 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1_7ad66e59518a | 2019-02-05 08:04:43.893 UTC [21] LOG:  database system was shut down at 2019-02-05 08:04:00 UTC
db_1_7ad66e59518a | 2019-02-05 08:04:43.948 UTC [1] LOG:  database system is ready to accept connections
db_1_7ad66e59518a | 2019-02-05 08:04:53.631 UTC [28] ERROR:  relation "uniq_model_model_type_vocab" already exists
db_1_7ad66e59518a | 2019-02-05 08:04:53.631 UTC [28] STATEMENT:  CREATE UNIQUE INDEX "uniq_model_model_type_vocab" ON "model" ("is of-vocabulary", "model type");
db_1_7ad66e59518a | 2019-02-05 10:03:51.465 UTC [29] ERROR:  duplicate key value violates unique constraint "service_application_service name_key"
db_1_7ad66e59518a | 2019-02-05 10:03:51.465 UTC [29] DETAIL:  Key (application, "service name")=(3, main) already exists.
db_1_7ad66e59518a | 2019-02-05 10:03:51.465 UTC [29] STATEMENT:  INSERT INTO "service" ("application", "service name")
db_1_7ad66e59518a | 	VALUES ($1, $2) RETURNING "id";
db_1_7ad66e59518a | 2019-02-05 10:19:40.570 UTC [153] ERROR:  duplicate key value violates unique constraint "service_application_service name_key"
db_1_7ad66e59518a | 2019-02-05 10:19:40.570 UTC [153] DETAIL:  Key (application, "service name")=(3, main) already exists.
db_1_7ad66e59518a | 2019-02-05 10:19:40.570 UTC [153] STATEMENT:  INSERT INTO "service" ("application", "service name")
db_1_7ad66e59518a | 	VALUES ($1, $2) RETURNING "id";
db_1_7ad66e59518a | 2019-02-05 14:21:43.482 UTC [170] ERROR:  duplicate key value violates unique constraint "service_application_service name_key"
db_1_7ad66e59518a | 2019-02-05 14:21:43.482 UTC [170] DETAIL:  Key (application, "service name")=(3, main) already exists.
db_1_7ad66e59518a | 2019-02-05 14:21:43.482 UTC [170] STATEMENT:  INSERT INTO "service" ("application", "service name")
db_1_7ad66e59518a | 	VALUES ($1, $2) RETURNING "id";
db_1_7ad66e59518a | 2019-02-05 15:41:34.369 UTC [418] ERROR:  duplicate key value violates unique constraint "service_application_service name_key"
db_1_7ad66e59518a | 2019-02-05 15:41:34.369 UTC [418] DETAIL:  Key (application, "service name")=(3, main) already exists.
db_1_7ad66e59518a | 2019-02-05 15:41:34.369 UTC [418] STATEMENT:  INSERT INTO "service" ("application", "service name")
db_1_7ad66e59518a | 	VALUES ($1, $2) RETURNING "id";
db_1_7ad66e59518a | 2019-02-05 17:14:31.193 UTC [611] FATAL:  canceling authentication due to timeout
db_1_7ad66e59518a | 2019-02-05 17:15:19.282 UTC [616] LOG:  could not receive data from client: Connection reset by peer
db_1_7ad66e59518a | 2019-02-05 17:15:20.803 UTC [616] LOG:  incomplete startup packet
db_1_7ad66e59518a | 2019-02-05 17:16:19.170 UTC [617] LOG:  could not receive data from client: Connection reset by peer
db_1_7ad66e59518a | 2019-02-05 17:17:55.275 UTC [619] LOG:  could not receive data from client: Connection reset by peer
db_1_7ad66e59518a | 2019-02-05 17:17:57.207 UTC [619] LOG:  incomplete startup packet
db_1_7ad66e59518a | 2019-02-05 17:18:01.695 UTC [581] LOG:  unexpected EOF on client connection with an open transaction
db_1_7ad66e59518a | 2019-02-05 17:18:02.799 UTC [607] LOG:  unexpected EOF on client connection with an open transaction
db_1_7ad66e59518a | 2019-02-05 17:18:02.799 UTC [606] LOG:  unexpected EOF on client connection with an open transaction
db_1_7ad66e59518a | 2019-02-05 17:18:02.799 UTC [608] LOG:  unexpected EOF on client connection with an open transaction
db_1_7ad66e59518a | 2019-02-05 17:18:02.799 UTC [605] LOG:  unexpected EOF on client connection with an open transaction
db_1_7ad66e59518a | 2019-02-05 17:18:05.497 UTC [620] LOG:  could not receive data from client: Connection reset by peer
db_1_7ad66e59518a | 2019-02-05 17:18:05.497 UTC [625] LOG:  could not receive data from client: Connection reset by peer
db_1_7ad66e59518a | 2019-02-05 17:18:05.497 UTC [626] LOG:  could not receive data from client: Connection reset by peer
db_1_7ad66e59518a | 2019-02-05 17:18:05.497 UTC [624] LOG:  could not receive data from client: Connection reset by peer
db_1_7ad66e59518a | 2019-02-05 17:18:05.497 UTC [621] LOG:  could not receive data from client: Connection reset by peer
db_1_7ad66e59518a | 2019-02-05 17:18:05.497 UTC [623] LOG:  could not receive data from client: Connection reset by peer
db_1_7ad66e59518a | 2019-02-05 17:18:05.497 UTC [622] LOG:  could not receive data from client: Connection reset by peer
api_1_ee9297901b5c | Systemd init system enabled.
registry_1_6c2b77e018bb | Systemd init system enabled.
vpn_1_4c6019e78747 | Systemd init system enabled.
haproxy_1_3e1d962649bf | [WARNING] 035/080447 (1) : Server backend_api/resin_api_1 is DOWN, reason: Layer4 connection problem, info: "Connection refused", check duration: 0ms. 0 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
haproxy_1_3e1d962649bf | [ALERT] 035/080447 (1) : backend 'backend_api' has no server available!
haproxy_1_3e1d962649bf | [WARNING] 035/080449 (1) : Server vpn-tunnel/balena_vpn is DOWN, reason: Layer4 connection problem, info: "Connection refused", check duration: 0ms. 0 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
haproxy_1_3e1d962649bf | [ALERT] 035/080449 (1) : proxy 'vpn-tunnel' has no server available!
haproxy_1_3e1d962649bf | [WARNING] 035/080453 (1) : Server vpn-tunnel/balena_vpn is UP, reason: Layer4 check passed, check duration: 0ms. 1 active and 0 backup servers online. 0 sessions requeued, 0 total in queue.
haproxy_1_3e1d962649bf | [WARNING] 035/080501 (1) : Server backend_api/resin_api_1 is UP, reason: Layer4 check passed, check duration: 0ms. 1 active and 0 backup servers online. 0 sessions requeued, 0 total in queue.
haproxy_1_3e1d962649bf | [WARNING] 035/171809 (1) : Server backend_api/resin_api_1 is DOWN, reason: Layer4 connection problem, info: "Connection refused", check duration: 0ms. 0 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
haproxy_1_3e1d962649bf | [ALERT] 035/171809 (1) : backend 'backend_api' has no server available!`

**Comment by dfunckt** [comment]
Hey @t16n, do you still have the issue? I'll be closing this, if you still need help please use [the forums](https://forums.balena.io/c/open-balena).
