### ISSUE TITLE
docker login: wrong realm returned on 401

### ISSUE THREAD

**Issue by umarovt** [balena-io/open-balena#41]
Hi,

I am trying to login into provided docker registry but token authorization is not working since the realm returned in the header is not populated with the domain name.

www-authenticate →Bearer realm="https://api./auth/v1/token",service="registry2."

I have changed and hardcoded environment variables in both docker-compose.yml and directly in services.yml, but nothing has changed. (next parameter: BALENA_TOKEN_AUTH_REALM).

Does somebody have any idea what I am doing wrong?

Thank you in advance.

Urban

**Comment by dfunckt** [comment]
Hey @umarovt, we prefer to keep the Github issue tracker for actionable items, can you please post your question [on the forums](https://forums.balena.io/c/open-balena) and close this?

**Comment by umarovt** [comment]
Thank you for your feedback. I will post it there as well, but still, I believe something is actually not working as expected here :)
