### ISSUE TITLE
Remove dependency on `coreutils` for realpath on macOS

### ISSUE THREAD

**Issue by dfunckt** [balena-io/open-balena#46]
We're using `realpath` in a few places in the scripts that manage the openBalena instance and that requires installation of `coreutils` on macOS. Ideally we'd skip this dependency.

One snippet I've been using for years (and has proven robust enough in macOS, where I've only  ever tested it) to get the absolute path of a script to itself -- i.e. the equivalent of C's `__FILE__` or Node's `__filename` -- is the following:

```sh
abspath() {
  (
    local foldername=$(dirname "$1")
    local filename=$(basename "$1")
    pushd "$foldername" >/dev/null
    echo "$PWD/$filename"
    popd >/dev/null
  )
}

# typically invoked like this from inside a script
MYVAR=$(abspath "$0")
```

I'm not sure off the top of my head what extra guarantees the actual `realpath` gives, but I don't think we really need anything more than an absolute path to use as an anchor for finding project-relative paths, so we could use this snippet as a basis.

**Comment by wrboyce** [comment]
Along a very similar vein, I've used this snippet a few times over the years

```bash
abspath() {
  echo "$(cd "$(dirname "$1")" && pwd)/$(basename "$1")"
}
```

Pretty much the same, but I have a subshell and you use popd.

Or if you're willing to venture out into a modern shell (zsh)…

```zsh
abspath() {
  echo "${1:A}"
}
```

😁

**Comment by roman-mazur** [comment]
I believe the main difference between what you guys suggest here and what `realpath` does is resolving links.

If the task is to obtain absolute path, and using links is not a problem, `realpath` should not be a dependency.

**Comment by ab77** [comment]
Superseded.
