### ISSUE TITLE
There is no included MDNS/DNS-SD functionality

### ISSUE THREAD

**Issue by hedss** [balena-io/open-balena#52]
The OpenBalena docs refer to a default `openbalena.local` domain, however there is no default ability to publish the hostnames as a `.local` domain.

We should include a publisher and default service setup so that this works 'out of the box'.

**Comment by dfunckt** [comment]
@richbayliss you recently addressed this one, is that right?

**Comment by ab77** [comment]
We've concluded that mDNS for openBalena doesn't really make sense and while it can be made to work, the additional overheads are not worth maintaining, especially considering the composition can (and should) be able to run in Kubernetes, etc. (where it's all DNS).
