### ISSUE TITLE
[Error] Running a simple-server-node in a UP-Board device. 

### ISSUE THREAD

**Issue by joashcabungcal** [balena-io/open-balena#55]
This is the error message.
time="2019-07-02T08:31:58.545306456Z" level=warning msg="failed to retrieve balena-engine-init version: exec: \"balena-engine-init\": executable file not found in $PATH"

**Repository**
https://github.com/balena-io-projects/simple-server-node

**Command I use to deploy**
balena deploy [AppName] --source --logs . --emulated
balena deploy [AppName]

**Versions**
balena-engine version 17.12.0-dev, build dceb2fc48071b78a8a828e0468a15a479515385f
UP board | BalenaOS 2.29.2+rev1 --- Development
Docker version 18.09.5, build e8ff056

The resin_supervisor container is running. But everytime I deploy the simple node server, it keeps on restarting. I also tried to deploy a simple Dockerfile. It still restarts

**simple Dockerfile**
FROM balenalib/up-board-debian

**Logfiles**
![image](https://user-images.githubusercontent.com/36874216/60498102-9228bd80-9ce8-11e9-8cdb-00addce609f3.png)

![image](https://user-images.githubusercontent.com/36874216/60498177-b5536d00-9ce8-11e9-86b3-b4d1dd1d141a.png)

![image](https://user-images.githubusercontent.com/36874216/60498204-c00e0200-9ce8-11e9-9d98-2053ad9511d8.png)

![image](https://user-images.githubusercontent.com/36874216/60498236-cc925a80-9ce8-11e9-98f3-36670612031a.png)

I don't know if the UP Board image is still buggy or the device that I use is defective. Could someone help me on this?

**Comment by dfunckt** [comment]
Hello, can you please seek help on our forums? We try to keep Github issues for actionable items only. They're located here: https://forums.balena.io/c/open-balena
