### ISSUE TITLE
Use multiple VPN instances

### ISSUE THREAD

**Issue by imrehg** [balena-io/open-balena#57]
User would like to use multiple VPN instances with OpenBalena to help connect many devices.

**Comment by dfunckt** [comment]
@wrboyce you recently added the ability to run VPN on many network interfaces, is that correct? Is there a way to expose this functionality to users?

**Comment by ab77** [comment]
A single `balena/open-balena-vpn` container will spawn multiple `OpenVPN` processes when `PRODUCTION_MODE=true` up to a maximum of `nproc`. The service can also [now](https://github.com/balena-io/open-balena-vpn/blob/master/src/utils/config.ts#L75) be configured for UDP listeners, though HAProxy would need to be bypassed (probably) and at the expense of having a single listener/process only
