### ISSUE TITLE
How to add dashboard

### ISSUE THREAD

**Issue by dpnkrg** [balena-io/open-balena#63]
Hi Community Members,

Is there any way to add a dashboard to openbalena. Balena dashboard or any custom dashboard?

**Comment by dpnkrg** [comment]
@balena-ci, Please add dashboard. Or help me to contribute how to add dashboard.

**Comment by macpijan** [comment]
Any news on the dashboard status? Is it on the roadmap somewhere, or openBalena is meant to be used without dashboard?

**Comment by dfunckt** [comment]
There are no plans to ship a web-based interface for openBalena — the primary interface is the CLI. We do however maintain a Javascript SDK (which the balenaCloud Dashboard uses extensively) that makes possible users or the community to build on top.

**Comment by Razikus** [comment]
Check this project
https://github.com/Razikus/open-balena-dashboard

If you want some functionality - raise an issue, or add it by yourself

**Comment by danclimasevschi** [comment]
https://github.com/dcaputo-harmoni/open-balena-admin

**Comment by ab77** [comment]
See [here](https://open-balena.pages.dev/#are-there-open-source-ui-dashboards-from-the-community-for-openbalena).
