### ISSUE TITLE
stuck at screen | no response for jetson nano

### ISSUE THREAD

**Issue by yogeshwar607** [balena-io/open-balena#64]
I have tried open-balena with both wifi and ethernet connectivity for jetson nano , it is stuck at below screen. No response for  balena devices command 
Master server is setup properly

![image](https://user-images.githubusercontent.com/10059011/63128531-c6271c00-bfd2-11e9-95c3-f0c8db982ef5.png)

![image](https://user-images.githubusercontent.com/10059011/63128651-156d4c80-bfd3-11e9-8901-e6b8997e826a.png)

**Comment by SjoerdTimovanVliet** [comment]
@yogeshwar607  How did you resolve this issue? having the same problem
