### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by aessig** [balena-io/open-balena#71]
Using what seems to be the latest version available of open-balena (2.0.0) and Balena CLI (11.19.1) I cannot push the image to the registry. The following error is displayed: 

```
Retrying "registry.mydomain.com/v2/XXXXXXXXXXXXXXXXXXXXXXX:latest" after 2.00s (1 of 3) due to: Error: received unexpected HTTP status: 500 Internal Server Error
Retrying "registry.mydomain.com/v2/XXXXXXXXXXXXXXXXXXXXXXX:latest" after 2.80s (2 of 3) due to: Error: received unexpected HTTP status: 500 Internal Server Error
Retrying "registry.mydomain.com/v2/XXXXXXXXXXXXXXXXXXXXXXX:latest" after 3.92s (3 of 3) due to: Error: received unexpected HTTP status: 500 Internal Server Error
```

Does anyone have an idea what could be the problem? Could it be linked with to the following issue?
https://github.com/docker/distribution-library-image/issues/89

**Comment by dfunckt** [comment]
It's been a while so I won't ask for further info, but regardless, support queries should go via the forums which are far higher bandwidth and monitored by the whole team.
