### ISSUE TITLE
RasPi 3 becoming "offline" while loading device configuration

### ISSUE THREAD

**Issue by ozymaxx** [balena-io/open-balena#76]
Hi, when I activate the "Enable / Disable VPN" setting, set it to "disabled", and restart my RasPi 3, then, during startup, the following log items show up and the device suddenly becomes "offline":

```
29.03.20 00:39:48 (+0100) Applying configuration change {"SUPERVISOR_VPN_CONTROL":"false"}
29.03.20 00:39:48 (+0100) Applied configuration change {"SUPERVISOR_VPN_CONTROL":"false"}
```

actually, it is not offline since I see the device running in front of me, and also, balena can still retrieve logs from the device.

**Comment by dfunckt** [comment]
Hello, can you please post your question in our forums instead? We prefer to reserve Github issues for actionable items only and can only provide support over at https://forums.balena.io/
