### ISSUE TITLE
Link back to the excellent getting-started guide from README

### ISSUE THREAD

**Issue by nmaas87** [balena-io/open-balena#8]
The README.md does show a very quick way to getting things setup, but it does leave out some important things like installation of nodejs / npm and the libssl-dev, which are probably needed for the CLI client. It could help new users if you link from the README.md to https://www.balena.io/open/docs/getting-started which explains in more detail how to setup open-balena 👍

**Comment by dfunckt** [comment]
627867a overhauled the README which also addressed this. Thanks!
