### ISSUE TITLE
openBalena incompatible with devices running balenaOS >2.49.0

### ISSUE THREAD

**Issue by xginn8** [balena-io/open-balena#80]

**Comment by dfunckt** [comment]
For clarity, the reason for this is that new Supervisors don’t send values expected by the register endpoint of the API shipped with openBalena. To resolve this we need to bump the API version. This will also bring breaking model changes though.

So we need three things:

- publish a new OData version (v6) exposing the new model
- update the Supervisor to use that new version
- bump the API version in openBalena and require a *minimum* version X of balenaOS, with X being the OS version that includes the new Supervisor.

This is long overdue but we're finally ready to publish v6 on balenaCloud as well, so the timing is perfect.

**Comment by Razikus** [comment]
Any information when the fix will be available?

**Comment by dfunckt** [comment]
I expect 3-4 weeks @Razikus.

**Comment by Razikus** [comment]
@dfunckt thank you very much

Would it be always like this? 
Now it makes the things harder and useless. 

Newest releases of balenaOS are incompatible with OpenBalena, so we can't use raspberry pi 4 image for examle.
OpenBalena is useless now for 4 weeks for these boards, am i right?

Can we expect a complex solution for this problem in future?

**Comment by dfunckt** [comment]
@Razikus, balenaOS versions before v2.49 continue to work just fine. Here is [v2.48 for the RPi 4](https://files.balena-cloud.com/images/raspberrypi4-64/2.48.0%2Brev1.prod/image/balena.img.zip).

**Comment by gerb0n** [comment]
Maybe notify people on the [download site](https://www.balena.io/os/) before they lose their sanity as to why it's not working (like I did).

**Comment by bartversluijs** [comment]
Is it an idea to have the ability to download older balenaOS releases (like in balenaCloud) on the download site @gerb0n mentioned? Or is there another way to get older balenaOS releases? :)

**Comment by gerb0n** [comment]
> Is it an idea to have the ability to download older balenaOS releases (like in balenaCloud) on the download site @gerb0n mentioned? Or is there another way to get older balenaOS releases? :)

Right now I am just changing the download url to the version you want. But that's not really user-friendly indeed. Would like that ability aswell.

**Comment by xavierchan** [comment]
Hi, @dfunckt . Can you tell me compatible image of raspberrypi3? I also encountered this situation.

**Comment by velosol** [comment]
> Is it an idea to have the ability to download older balenaOS releases (like in balenaCloud) on the download site @gerb0n mentioned? Or is there another way to get older balenaOS releases? :)

I used balena-cli to figure out the slug of the image I needed to download by using the following (note you [can't actually download images when using openBalena](https://forums.balena.io/t/unable-to-download-balenaos-images-using-pythonsdk/52409/23))
`balena os download raspberrypi3 -o pi.img --version menu`

which displays

>Select the OS version:
>\> v2.47.0+rev1.prod (recommended)
   &nbsp;&nbsp; v2.47.0+rev1.dev
...

Then over to https://www.balena.io/os and find the current download link, e.g. 
`https://api.balena-cloud.com/download?deviceType=raspberrypi3&version=2.53.9+rev1.dev&fileType=.zip` and edit it to 
`https://api.balena-cloud.com/download?deviceType=raspberrypi3&version=2.47.0+rev1.dev&fileType=.zip`

**Comment by bartversluijs** [comment]
Is there any update on this?

**Comment by maggie0002** [comment]
While we wait for these changes, are there any suggested approaches for those of us deploying devices in the short term? Is there a way to configure and pre-load a >2.49.0 image today which in the short term will not connect to OpenBalena because of the out of date API, but will be sitting there ready to connect when the new OpenBalena is released and installed? 

A combination of a lack of OS update features and the new API being the basis for the foreseeable future makes me wary of launching and deploying devices today that will ultimately be out of date and cannot be updated in the near future.

**Comment by dfunckt** [comment]
Fixed by #88. Note that existing devices will not be fully functional until reprovisioned to at least balenaOS v2.58.3.
