### ISSUE TITLE
Unable to login to openbalena instance

### ISSUE THREAD

**Issue by ericmjl** [balena-io/open-balena#81]
Hello Balena team!

First off, thank you for putting balena out as an open source project!

I have followed [the docs][docs] exactly to get Balena up and running on DigitalOcean, but I am always hitting a wall getting stuck at logging in.

In particular, I was most unsure about CNAME records. My CNAME records are set up, and I think they are set up correctly. Base domain is `mydomain.org` (I am masking the actual domain in this post), and I have CNAME records for `api`, `s3`, `vpn`, and `registry` on Google Domains, with `api` pointing to `api.mydomain.org` etc. SSL is enabled for `mydomain.org`, which forwards directly to my DigitalOcean box's IP address.

However, even with all of this set up, I still get the following error logging in.

```
ENOTFOUND: request to https://api.mydomain.org/login_ failed, reason: getaddrinfo ENOTFOUND api.mydomain.org api.wors
hip-manager.org:443
```

I understand that the issue may need some digging before I can get past this blocker to using open-balena. What would be the best starting points for debugging? To be clear, I'm not expecting to resolve this quickly, but would like to take this chance to learn more about the right process of debugging the installation process. I might then take the chance to contribute some docs back.

[docs]: https://www.balena.io/open/docs/getting-started/

**Comment by dfunckt** [comment]
Hello, can you please repost your question on our [forums](https://forums.balena.io/c/open-balena)? We reserve Github issues for actionable items and all support issues should be directed to the forums instead.

**Comment by ericmjl** [comment]
Done, thanks for getting back!
