### ISSUE TITLE
User ID must be a valid integer

### ISSUE THREAD

**Issue by hannahaddad** [balena-io/open-balena#82]
Hey guys,

I am running latest open-balena, balena cli version 12.9.1 and trying to provision balena-cloud-fincm3-2.51.1+rev1-v11.4.10.img on a BalenFin v1.1.

The supervisor on that box keeps spitting the following and it's failing to register the device,

`[event]   Event: Device bootstrap failed, retrying {"delay":30000,"error":{"message":"User ID must be a valid integer","stack":"Error: User ID must be a valid integer\n    at /usr/src/app/dist/app.js:2:2630094\n    at PassThroughHandlerContext.finallyHandler (/usr/src/app/dist/app.js:2:1748917)\n    at PassThroughHandlerContext.tryCatcher (/usr/src/app/dist/app.js:2:220284)\n    at Promise._settlePromiseFromHandler (/usr/src/app/dist/app.js:2:1708447)\n    at Promise._settlePromise (/usr/src/app/dist/app.js:2:1709730)\n    at Promise._settlePromise0 (/usr/src/app/dist/app.js:2:1710770)\n    at Promise._settlePromises (/usr/src/app/dist/app.js:2:1712478)\n    at _drainQueueStep (/usr/src/app/dist/app.js:2:1715412)\n    at _drainQueue (/usr/src/app/dist/app.js:2:1715308)\n    at Async._drainQueues (/usr/src/app/dist/app.js:2:1716625)\n    at Immediate.Async.drainQueues [as _onImmediate] (/usr/src/app/dist/app.js:2:1715217)\n    at processImmediate (internal/timers.js:456:21)"}}`

this is how i am configuring the image

`balena os configure ~/Downloads/balena-cloud-fincm3-2.51.1+rev1-dev-v11.4.10.img --app foo`

any idea?
Thanks

**Comment by PastaGringo** [comment]
Hi,
You need to use only balenaos version < 2.48.

**Comment by hannahaddad** [comment]
@PastaGringo thank you for the quick response. where can i find the old versions?

**Comment by PastaGringo** [comment]
It's tricky. You can get it from the balenacloud console or play with URL from the openbalena release page.

**Comment by hannahaddad** [comment]
thank you 

[2.48.0 prod](https://api.balena-cloud.com/download?deviceType=fincm3&version=2.48.0.prod&fileType=.zip)

**Comment by xginn8** [comment]
Closing in favor of https://github.com/balena-io/open-balena/issues/80
