### ISSUE TITLE
open-balena ports 80 and 443 interferes with existing nginx-revproxy

### ISSUE THREAD

**Issue by beasteers** [balena-io/open-balena#91]
I'm looking to migrate a project over to `open-balena`, but currently we have [nginx-proxy](https://hub.docker.com/r/jwilder/nginx-proxy) running on `80/443` that automatically detects (server-side) docker containers and will redirect requests based on `VIRTUAL_HOST=app-A.domain.com` and `VIRTUAL_PORT=8888` environment variables defined inside each container (and handles letsencrypt too).

Does `open-balena` handle any deployments of server-side containers (e.g. dashboards, data ingestion)? If so, it would be great if the built-in `haproxy` were able to automatically register launched containers and redirect requests on port `80/443` to custom urls. You could do this using `docker-gen` (like `nginx-proxy` does) to re-generate `haproxy.cfg` then SIGHUP when a new container is created. You could do something like `BALENA_PROXY_HOST / BALENA_PROXY_PORT`.

If that's not an intended usage and `open-balena` is meant to be more limited in scope, then it would be useful to be able to run a balena server alongside containers that do cover this usage, meaning that I'd like to find a way to either redirect requests through nginx-proxy to haproxy or the other way around, but I'm not sure if that's possible. 

Personally, my preference is for the first option because it doesn't involve having to run and manage two web servers. But that would also mean handling automatic LetsEncrypt (which I think you already do for the other endpoints). Side note, just because it may affect things like certificates, I'd like to have the ability to have `api.balena.domain.com` for the balena-specific endpoints and (e.g.) `elasticsearch.domain.com` so that the apps don't have to be subdomains of `*.balena`.

I'm wondering what your thoughts are on this and how it fits into the roadmap of `open-balena`

**Comment by dfunckt** [comment]
I think this (either way, in fact) isn't currently possible mostly because of the way devices interact with the backend, but I'm not scoring high on networking so I may be missing obvious solutions.

Regardless, this [isn't the right place to discuss this](https://github.com/balena-io/open-balena#getting-help) -- so I'll be closing the issue. The best place is on our forums where you can tap on the knowledge of our whole team.
