### ISSUE TITLE
No upgrade path for OpenBalena.

### ISSUE THREAD

**Issue by jimmyw** [balena-io/open-balena#92]
Hi.

In OpenBalena 2.* series, the maximum supported os version of Balena os was 2.48
In OpenBalena 3.* series, the minimum supported os version of Balena is 2.58.3

So my question is, how do I upgrade my production devices? I can't upgrade them to 2.58.3 before upgrading the server, because they won't work. I can't upgrade the server before upgrading the devices because the server won't work with older ones.

What is the main reason for pre 2.58.3 versions of Balena is not working if I upgrade the server?

**Comment by dfunckt** [comment]
Please use the forums for this type of queries. To briefly answer your question, your devices will keep running your application regardless of whether they can reach the backend or not. This is a core tenet of the platform. What cannot be (currently) guaranteed with openBalena is that you will also be able to monitor, manage or update them until the minimum requirements are met.

**Comment by jimmyw** [comment]
Is it not an issue, that after upgrading OpenBalena, you will lose connection to all your balena devices you har having?

Shoud you not state on in the README, that all users that have a deployment of OpenBalena 2.0 need to stay on that version forever?

**Comment by dfunckt** [comment]
Arguably, it could be an issue in a production setting for which openBalena is not ready yet, as clearly stated in the README.

I'm closing the issue -- if you have further questions that we can help with, please use the forums.
