### ISSUE TITLE
Devices communicate but do not pull application

### ISSUE THREAD

**Issue by SteeveGL** [balena-io/open-balena#98]
Everything seems to be well configure. I can logs in to the device. But it does'nt pull the app

```
$ balena devices
ID UUID    DEVICE NAME DEVICE TYPE     APPLICATION NAME STATUS IS ONLINE SUPERVISOR VERSION OS VERSION DASHBOARD URL
1  c3e2e4a empty-bush  raspberrypi3-64 myApp            N/a    true      N/a                N/a        https://dashboard.balena.mydomain.co/devices/c3e2e4a7a078e1210e9ae4cc75cd4dbd/summary
```
```
$ balena device c3e2e4a
== EMPTY BUSH
ID:                1
DEVICE TYPE:       raspberrypi3-64
STATUS:            idle
IS ONLINE:         true
APPLICATION NAME:  myApp
LAST SEEN:         2020-11-10T17:09:36.216Z
UUID:              c3e2e4a7a078e1210e9ae4cc75cd4dbd
COMMIT:            N/a
IS WEB ACCESSIBLE: false
DASHBOARD URL:     https://dashboard.balena.mydomain.co/devices/c3e2e4a7a078e1210e9ae4cc75cd4dbd/summary
```
```
$ balena logs c3e2e4a
[Logs]    [11/10/2020, 12:09:49 PM] Supervisor starting
```

But I noticed some 404 and 401 in the logs, I don't know if it's related.
This is when I boot up the device
```
...
Nov 10 17:35:01 b89942b5e807 api[982]: 2020-11-10T17:35:01.052Z 192.222.225.40 - POST /v5/device_config_variable 404 11.789ms -
...
Nov 10 17:35:10 b89942b5e807 api[982]: 2020-11-10T17:35:10.939Z 172.18.0.8 a/1 POST /resin/device(@id)/canAccess?@id=1 401 20.703ms -

```

```
$ cat compose/versions
export OPENBALENA_API_VERSION_TAG=v0.109.2
export OPENBALENA_DB_VERSION_TAG=v4.1.0
export OPENBALENA_MDNS_PUBLISHER_VERSION_TAG=v1.7.9
export OPENBALENA_REGISTRY_VERSION_TAG=v2.13.11
export OPENBALENA_S3_VERSION_TAG=v2.9.9
export OPENBALENA_VPN_VERSION_TAG=v9.16.1
```

**Comment by dfunckt** [comment]
The commands are from different stages in the provisioning flow and it's hard to correlate things. I'd make sure the OS is recent enough (ie. >=2.59) and look into the device logs by SSH'ing into the device and running "journalctl -fn300".

**Comment by SteeveGL** [comment]
> The commands are from different stages in the provisioning flow and it's hard to correlate things. I'd make sure the OS is recent enough (ie. >=2.59) and look into the device logs by SSH'ing into the device and running "journalctl -fn300 -uresin-supervisor".

Thanks, you helped me out.

I was using the Raspberry Pi 3 64 version, but the image is out dated... I didn't notice that section: https://github.com/balena-io/open-balena#compatibility
